version: '3.8'

services:
  # 1. PostgreSQL Database Server (Exposed on 5432)
  postgres:
    image: postgres:15-alpine
    container_name: telemed-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # El default database es 'postgres', Prisma creará el resto automáticamente al sincronizar!
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. PGAdmin 4 - Base de Datos Panel de Administración (Puerto 8080)
  pgadmin:
    image: dpage/pgadmin4
    container_name: telemed-pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres

  # 3. API Gateway
  api-gateway:
    build:
      context: ./services
      dockerfile: ./apps/services/Dockerfile
    container_name: telemed-api-gateway
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - GATEWAY_PORT=8000
      - AUTH_SERVICE_PORT=8001
      - APPOINTMENT_SERVICE_PORT=8002
      - CLINICAL_HISTORY_SERVICE_PORT=8003
      - AUTH_SERVICE_URL=http://auth-service:8001
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8002
      - CLINICAL_HISTORY_SERVICE_URL=http://clinical-history-service:8003
      - JWT_SECRET=jwt-telemedicina-ultra-secret-key-xyz
      - ENCRYPTION_KEY=ab12cd34ef56gh78ij90kl12mn34op56
    depends_on:
      - auth-service
      - appointment-service
      - clinical-history-service

  # 4. Auth Service
  auth-service:
    build:
      context: ./services
      dockerfile: ./apps/auth-service/Dockerfile
    container_name: telemed-auth-service
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=production
      - AUTH_SERVICE_PORT=8001
      - JWT_SECRET=jwt-telemedicina-ultra-secret-key-xyz
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/telemed_auth?schema=public
    depends_on:
      - postgres

  # 5. Appointment Service
  appointment-service:
    build:
      context: ./services
      dockerfile: ./apps/appointment-service/Dockerfile
    container_name: telemed-appointment-service
    ports:
      - "8002:8002"
    environment:
      - NODE_ENV=production
      - APPOINTMENT_SERVICE_PORT=8002
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/telemed_appointments?schema=public
    depends_on:
      - postgres

  # 6. Clinical History Service
  clinical-history-service:
    build:
      context: ./services
      dockerfile: ./apps/clinical-history-service/Dockerfile
    container_name: telemed-clinical-history-service
    ports:
      - "8003:8003"
    environment:
      - NODE_ENV=production
      - CLINICAL_HISTORY_SERVICE_PORT=8003
      - ENCRYPTION_KEY=ab12cd34ef56gh78ij90kl12mn34op56
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/telemed_clinical_history?schema=public
    depends_on:
      - postgres

  # 7. Frontend React SPA
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: telemed-frontend
    ports:
      - "5173:80"
    depends_on:
      - api-gateway

volumes:
  postgres_data:
